name: deploy

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/ronalfcito/flask-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Iniciar sesión en GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ronalfcito
          password: ${{ secrets.GHCR_PAT }}

      - name: Construir y publicar imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:2.0.0
            ${{ env.IMAGE_NAME }}:latest

      - name: "mostrar datos de conexión (sin secretos sensibles)"
        run: |
          echo "probando la conexión con SSH con:"
          echo "Host: ${{ secrets.VPS_HOST }}"
          echo "usuario: ${{ secrets.VPS_USER }}"
          echo "puerto: ${{ secrets.VPS_SSH_PORT }}"
          echo "password: [OCULTO POR SEGURIDAD]"

      - name: "probar conexión SSH al VPS"
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "probando la conexión con SSH EN EL VPS"
            touch quitoa.txt

      - name: "pasar archivos desde git al vps"
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: "stack.yml,Makefile"
          target: "/home/${{ secrets.VPS_USER }}/despliegue"

      - name: Despliegue de los servicios
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          timeout: 600
          script: |
            echo " Desplegando servicios"
            docker login ghcr.io -u ronalfcito -p ${{ secrets.GHCR_PAT }}
            docker pull ghcr.io/ronalfcito/flask-app:latest
            docker stack deploy -c /home/${{ secrets.VPS_USER }}/despliegue/stack.yml ronald
