name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login my-registry.com -u ${{ secrets.REGISTRY_USER }} --password-stdin

      - name: Build Docker image
        run: docker build -t my-registry.com/pagina-ronald:latest .

      - name: Push Docker image
        run: docker push my-registry.com/pagina-ronald:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull my-registry.com/pagina-ronald:latest
            docker stop pagina-ronald || true
            docker rm pagina-ronald || true
            docker run -d --name pagina-ronald -p 5000:5000 my-registry.com/pagina-ronald:latest
